[Event]OnPCGuildLeaveFilter 当玩家离开公会(无论是自愿还是被踢)，触发此过滤器 [聽風]
PandasWS/Pandas pull request #419
Opened 2021-09-05 05:52 UTC by michaelwoooo

* **Addressed Issue(s)**: 

* **Server Mode**: 

* **Description of Pull Request**:

2021-09-05 13:23 UTC, CairoLee requested changes
有一些修改的建议，可以看一下~ 方便的话就修了吧。也算熟悉了一次 review 的流程

2021-09-05 13:23 UTC, CairoLee commented on doc/pandas_events.txt
> +	队长踢出公会的关联到队长
看起来应该和队长没啥关系，想表达的是“会长”？

2021-09-05 13:23 UTC, CairoLee commented on .gitignore
> +/npc
与 gitignore 这个文件相关的这两行改动直接撤销掉吧~

2021-09-05 13:23 UTC, CairoLee commented on doc/pandas_events.txt
> +	@left_guild_kick	是否是被会长踢出
给出可能的值说明，比如（0 - 玩家自己退出公会；1 - 被会长从公会驱逐）

2021-09-05 13:23 UTC, CairoLee commented on doc/pandas_events.txt
> +	@left_guild_aid		离开公会玩家的Aid
在熊猫里aid统一翻译成：账号编号（可参照：OnPCViewEquipFilter 的说明）

2021-09-05 13:23 UTC, CairoLee commented on src/map/guild.cpp
> +	if (sd) {
再多判断一个 g 指针是否有效（虽然看起来没啥鸟用，但其实 g 自己是否会释放完全看其他环节代码有没有问题，我们可以假定不信任他们，这样会更健壮）

2021-09-05 13:23 UTC, CairoLee commented on src/map/guild.cpp
> +	if (sd) {
同上，建议对 g 指针的有效性进行检查，确保 g 指针非空

2021-09-05 13:23 UTC, CairoLee commented on src/map/npc.cpp
> +		NPCF_GUILDLEAVE,	// guildleave_filter_name	// OnPCGuildLeaveFilter		// 当玩家离开公会(无论是自愿还是被踢)，触发此过滤器 [聽風]
注释中的中文遇到标点符号的时候，请用英文的标点符号~ 后面几个同理

2021-09-05 13:23 UTC, CairoLee commented on src/config/pandas.hpp
> +		// 当玩家离开公会(无论是自愿还是被踢)，触发此过滤器 [聽風]
将中文的“，”逗号，换成英文的逗号加一个空格：“, ”

2021-09-05 14:49 UTC, michaelwoooo commented on .gitignore
> +/npc
不会撤。。。

2021-09-07 05:40 UTC, CairoLee approved these changes

2021-09-07 05:46 UTC, merged